[[SCIP_PaPILO]]
arch = "aarch64"
git-tree-sha1 = "833fbe1d30e4895fc7c3460ef0e6f95b2ba36fb6"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCIP_PaPILO.download]]
    sha256 = "4dd43109a39670237d4fd9e239a6df3f2d4f3b6f89bca2722dc9af3fe16e3b35"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee36d8185aad951ded551f4438b99e876606c00f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "80557f24ead24d893363ddf1d2852e1224dd3072a995c231a0bba702f3739e4b"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fe210be8c1819b1b1d2358561dd51ccfd1892c9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "b2696c470e1c1516c13e24131cb7c53f09680ee67b895d44507e5c7475d6135a"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "192b20299c27af187a8170da26e241ecb97de23c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "d65106870431c528d30d84662497e8e3e267b82453df187319cb0520f88cca7a"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aa7b5e92cc3173496b390de74fc9df93dceeefa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "2aa3d4d8b20f59b4704d2891924c2c5b29be30bb3751cd7546dce9366b8b22c8"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57b81b8f8c90b820888091546b3d2daa05981bbc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "d1d4e2b442b2d81f2380b60e436b7d16e841788d37dd972f9b3185d756b5c912"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56d4487aa277ab097539e510d549c6a0aef75033"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "b292d47720fb1250e386da0a6b834e9f3aba1664544fa73524de2231fee92f77"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4363237352e49281d4ce4e1d2a4cfadb3f47279f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "dd0e5c970da3036c027f2dcd4d80a60c42d0d2e7bfe741c15612e1a57743d661"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3d1359fd0ac1e7dc01ccd68a105ebb3524dd0d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "26ab39b6a1d6dbc5910aa7bbda42f08ad5bd7c179ab8402f9ce43eb7db9344ac"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ebecc461fb01f12f58d566a957164a5970158d8"
libgfortran_version = "5.0.0"
os = "windows"

    [[SCIP_PaPILO.download]]
    sha256 = "d10cb286acc77e1d732448a602326bc2ebc762ef6192a7e6f67af48dc6f0ca20"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fdc945eb198cd6a559644f94972e3ac60eff1ec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "40ce6f5529e7b9a25cd0ed53e87789bf7b5d2daaa3f549d3aa8963d688bb09d9"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
git-tree-sha1 = "b58712ee5350e7cb30c73c0d64bebfb30094a4a8"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCIP_PaPILO.download]]
    sha256 = "321db042166c07376884e1e22046049bd1b722855893b589d0ce7c6e756cf152"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4b9fb9a16315161a7cbdcd6bd41d59d13054466"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "ac4a474421d064c25b747a65c00b9bff9e1f17b2e3b498b558ded0faf2cca70f"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee6a2dd8fa367123e2f1d149d6098b4e583eedcb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCIP_PaPILO.download]]
    sha256 = "1790c99dcbc6a68a25808ca787a20301af0905bef096145b6eec4bb7ac0cd356"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
git-tree-sha1 = "7f4af562936e5453474dcda3ac1f3277aec26f00"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SCIP_PaPILO.download]]
    sha256 = "4a8193fd785a36284d9d8e0e252e52e150d5467756a72c2256ea5efbbebc82a6"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SCIP_PaPILO]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85e60c349a537c6aa7e3e1bab2780e333b8be6da"
libgfortran_version = "5.0.0"
os = "windows"

    [[SCIP_PaPILO.download]]
    sha256 = "8f3e5f3c3d32f15161ca23958dfafadc11a62784cd4c30892456ef36576348ef"
    url = "https://github.com/JuliaBinaryWrappers/SCIP_PaPILO_jll.jl/releases/download/SCIP_PaPILO-v1000.0.300+0/SCIP_PaPILO.v1000.0.300.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
