# Autogenerated wrapper script for SCIP_PaPILO_jll for i686-w64-mingw32-libgfortran5-cxx11
export libscip, papilo, scip

using bliss_jll
using boost_jll
using Bzip2_jll
using CompilerSupportLibraries_jll
using GMP_jll
using Ipopt_jll
using MPFR_jll
using OpenBLAS32_jll
using oneTBB_jll
using Readline_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("SCIP_PaPILO")
JLLWrappers.@declare_library_product(libscip, "libscip.dll")
JLLWrappers.@declare_executable_product(papilo)
JLLWrappers.@declare_executable_product(scip)
function __init__()
    JLLWrappers.@generate_init_header(bliss_jll, boost_jll, Bzip2_jll, CompilerSupportLibraries_jll, GMP_jll, Ipopt_jll, MPFR_jll, OpenBLAS32_jll, oneTBB_jll, Readline_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libscip,
        "bin\\libscip.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        papilo,
        "bin\\papilo.exe",
    )

    JLLWrappers.@init_executable_product(
        scip,
        "bin\\scip.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
